### ISSUE TITLE
Namespaces with embedded LUI correction

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/cloud-hq-web-frontend#19]
We need to find a way, on the frontend, to detect when we are displaying information of a namespace embedded in LUI so we can correct the information we show for entries like https://registry.identifiers.org/registry/vario#!, where sample ID is VariO:0294 and not 0294

**Comment by mbdebian** [comment]
@javfg , what are your thoughts on this one?

**Comment by javfg** [comment]
This should not be treated on the frontend, otherwise API calls will return wrong values when accessed directly.

**Comment by mbdebian** [comment]
This has also been reported by other users and it's now solved.
