### ISSUE TITLE
Missing ROR ID in institutional details.

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/cloud-hq-web-frontend#30]
When working on the curation dashboard, if a ROR ID is added to the prefix registration request, it looks like it's not being persisted upon confirmation of the prefix registration request amendment.

**Comment by renatocjn** [comment]
I attested that editing the ROR id from the curation dashboard works well but it is not possible to edit it from the namespace details page. I think this is not a problem so I'm closing this.
